### PR TITLE
Handle disk with non-512 logical sector size

### PR DESCRIPTION
**Pull request by cyruslien**
https://bugs.launchpad.net/somerville/+bug/2015958

mkfs.msdos has trouble handling cluster calculations for non-512 byte logical sectors. Need to force one sector per cluster to avoid the issue.

### CODE REVIEW

**Comment by cyruslien** [comment]
@CragW,
Please help to review it, thank you!

**Comment by CragW** [comment]
In contast to fix `1` sector for a cluster, it's a good time to change the file-system format from existing `msdos`/`fat16` to `fat32`. Would it work for you?

**Comment by cyruslien** [comment]
> 

Yes, switching to FAT32 also works for the issue. But switching to FAT32 needs to extend esp to 270M, I'm not sure if extending esp impacts the factory process. If it doesn't impact the factory process switching to FAT32 is a better solution.

**Comment by CragW** [comment]
> Yes, switching to FAT32 also works for the issue. But switching to FAT32 needs to extend esp to 270M, I'm not sure if extending esp impacts the factory process. If it doesn't impact the factory process switching to FAT32 is a better solution.

It's fine to increase the partition size from `250` to `270` and change the filesystem type from `mkfs.msdos` to `mkfs.vfat` (and please include the RP at later lines).  If it works on your end can you please resend the patch?

```
        command = ('mkfs.msdos', '-n', 'OS', self.device + rp_part)
```

**Comment by cyruslien** [comment]
> > Yes, switching to FAT32 also works for the issue. But switching to FAT32 needs to extend esp to 270M, I'm not sure if extending esp impacts the factory process. If it doesn't impact the factory process switching to FAT32 is a better solution.
> 
> It's fine to increase the partition size from `250` to `270` and change the filesystem type from `mkfs.msdos` to `mkfs.vfat` (and please include the RP at later lines). If it works on your end can you please resend the patch?
> 
> ```
>         command = ('mkfs.msdos', '-n', 'OS', self.device + rp_part)
> ```

Ok ok, I will resend the patch. Thanks!

**Comment by cyruslien** [comment]
> > > Yes, switching to FAT32 also works for the issue. But switching to FAT32 needs to extend esp to 270M, I'm not sure if extending esp impacts the factory process. If it doesn't impact the factory process switching to FAT32 is a better solution.
> > 
> > 
> > It's fine to increase the partition size from `250` to `270` and change the filesystem type from `mkfs.msdos` to `mkfs.vfat` (and please include the RP at later lines). If it works on your end can you please resend the patch?
> > ```
> >         command = ('mkfs.msdos', '-n', 'OS', self.device + rp_part)
> > ```
> 
> Ok ok, I will resend the patch. Thanks!



> > > Yes, switching to FAT32 also works for the issue. But switching to FAT32 needs to extend esp to 270M, I'm not sure if extending esp impacts the factory process. If it doesn't impact the factory process switching to FAT32 is a better solution.
> > 
> > 
> > It's fine to increase the partition size from `250` to `270` and change the filesystem type from `mkfs.msdos` to `mkfs.vfat` (and please include the RP at later lines). If it works on your end can you please resend the patch?
> > ```
> >         command = ('mkfs.msdos', '-n', 'OS', self.device + rp_part)
> > ```
> 
> Ok ok, I will resend the patch. Thanks!

@CragW, I send another PR https://github.com/dell/dell-recovery/pull/180 to switch to FAT32, please help to review. Thanks!

**Comment by cyruslien** [comment]
Close this PR and switch ESP to FAT32. https://github.com/dell/dell-recovery/pull/180

**Pull request closed without merging**
