### PR TITLE
We need these patches to fix some problems for fish packages.

### PR DESCRIPTION
**Pull request by fourdollars**

### CODE REVIEW

**Comment by superm1** [comment]
Can you please describe some more about the situation requiring emergency scripts even earlier?
@kevinkellyspacey can you please review these patches?

**Comment by fourdollars** [comment]
The issue happens in pool.sh.
It can not be fixed by providing newer dell-recovery because the pool.sh is broken that makes us unable to update dell-recovery.
If we have a early emergency script, that makes the debug process easier.

**Comment by kevinkellyspacey** [comment]
@superm1 OK. we need @fourdollars to provide the detail test case of this update for us to check. 
@fourdollars Would u please open an LP bug of this issue's details? It will help us to track and isolate your update.

**Comment by fourdollars** [comment]
Please follow https://bugs.launchpad.net/somerville/+bug/1754279

**Comment by fourdollars** [comment]
@kevinkellyspacey Did you see the LP bug?

**Comment by kevinkellyspacey** [comment]
@fourdollars yes, we will validate it till the bionic image is ready from your side next week as the LP's description shows

**Comment by fourdollars** [comment]
@kevinkellyspacey How is the progress now?
If dell-recovery doesn't include the fix, it makes the bionic base image unable to use any manifest.

**Comment by kevinkellyspacey** [comment]
@fourdollars after we got the latest base image, we have validated the fix patch is needed. Otherwise, the manifest will not be able to install. 
@superm1 I believe this fix is reasonable to include in our dell-recovery for 18.04.

**Pull request merged**
