### PR TITLE
Keep using isolinux for legacy BIOS, and embed the platform and revis…

### LINKED ISSUE #35: /usr/share/dell/bin/dell-bto-autobuilder generates ISO images with wrong partition ID.
There is no obvious side effect from this issue so far.

```
$ file italia_X80.iso
italia_X80.iso: DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'ISOIMAGE' (bootable); partition 1 : ID=0x83, start-CHS (0x0,0,1), end-CHS (0x3fb,128,32), startsector 0, 4210560 sectors; partition 2 : ID=0xef, start-CHS (0x3fc,0,1), end-CHS (0x3fd,128,32), startsector 4210560, 8256 sectors
```
```
$ fdisk -l italia_X80.iso 
Disk italia_X80.iso: 2 GiB, 2160033792 bytes, 4218816 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device          Boot   Start     End Sectors Size Id Type
italia_X80.iso1            0 4210559 4210560   2G 83 Linux
italia_X80.iso2      4210560 4218815    8256   4M ef EFI (FAT-12/16/32)
```
```
$ file ubuntu-16.04.3-desktop-amd64.iso
ubuntu-16.04.3-desktop-amd64.iso: DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Ubuntu 16.04.3 LTS amd64' (bootable); partition 2 : ID=0xef, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 3006684, 4672 sectors
```
```
$ fdisk -l ubuntu-16.04.3-desktop-amd64.iso
Disk ubuntu-16.04.3-desktop-amd64.iso: 1.5 GiB, 1587609600 bytes, 3100800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x0d66cd15

Device                            Boot   Start     End Sectors  Size Id Type
ubuntu-16.04.3-desktop-amd64.iso1 *          0 3100799 3100800  1.5G  0 Empty
ubuntu-16.04.3-desktop-amd64.iso2      3006684 3011355    4672  2.3M ef EFI (FAT-12/16/32)
```

(Edited to place in triple tick code blocks)

### PR DESCRIPTION
**Pull request by fourdollars**
…ion information in the ISO image. (Closes #35)

### CODE REVIEW

**Comment by fourdollars** [comment]
Sorry. This commit still has some problem that needs to fix.

**Comment by fourdollars** [comment]
I made some mistake during the verification.
This commit works fine.

**Comment by fourdollars** [comment]
Yes, I have modified it in OSP1 base image.

**Comment by fourdollars** [comment]
The modification for live-build configuration.

```
=== modified file 'binary'
--- binary      2016-03-02 05:08:52 +0000
+++ binary      2017-09-13 09:33:57 +0000
@@ -135,7 +135,7 @@
 
 # $LB_SYSLINUX_TIMEOUT: set custom syslinux timeout in seconds
 # (Default: 0)
-LB_SYSLINUX_TIMEOUT="1"
+LB_SYSLINUX_TIMEOUT="0"
 
 # $LB_SYSLINUX_CFG: set custom syslinux configuration file
 # (Default: empty)

=== modified file 'binary_local-hooks/90copy-isolinux-files'
--- binary_local-hooks/90copy-isolinux-files    2016-03-14 05:50:12 +0000
+++ binary_local-hooks/90copy-isolinux-files    2017-09-13 09:33:57 +0000
@@ -3,7 +3,7 @@
 set -e
 
 SYSLINUX_LIB=/usr/lib/syslinux/modules/bios
-ISOLINUX_FILES="ldlinux.c32 libcom32.c32 libutil.c32 vesamenu.c32"
+ISOLINUX_FILES="ldlinux.c32 libcom32.c32 libutil.c32 vesamenu.c32 reboot.c32"
 
 for f in $ISOLINUX_FILES; do
    [ -f chroot/${SYSLINUX_LIB}/${f} ] && \

=== modified file 'binary_local-hooks/90mangle-syslinux-menu'
--- binary_local-hooks/90mangle-syslinux-menu   2016-03-14 05:48:56 +0000
+++ binary_local-hooks/90mangle-syslinux-menu   2017-09-13 09:33:57 +0000
@@ -22,12 +22,11 @@
 #grep --line-regexp --after-context=4 "label auto" "${LIVE_CFG}" | sed 's/menu label Text Auto/menu label Press Enter to Install/' >> "${LIVE_CFG}".new
 #mv "${LIVE_CFG}".new "${LIVE_CFG}"
 
-# change text "Boot menu" to "Ubuntu 16.04 LTS for OEMs"
 cat > binary/isolinux/menu.cfg << EOF
 menu hshift 15
 menu width 49
 # ---------
-menu title Ubuntu 16.04 LTS for OEMs
+menu title Not Support Legacy BIOS
 include stdmenu.cfg
 include live.cfg
 EOF

=== modified file 'binary_local-includes/isolinux/live.cfg'
--- binary_local-includes/isolinux/live.cfg     2015-04-22 08:11:06 +0000
+++ binary_local-includes/isolinux/live.cfg     2017-09-13 09:33:57 +0000
@@ -1,4 +1,4 @@
 label auto
-menu label Press Enter to Install
-kernel /casper/vmlinuz.efi
-append noprompt initrd=/casper/initrd.lz boot=casper automatic-ubiquity quiet splash file=/cdrom/install/preseed.cfg -- radeon.modeset=0 nouveau.modeset=0
+menu label Press Enter to Reboot
+com32 reboot.c32
+append --warm

```

**Comment by superm1** [comment]
Sounds good

**Pull request merged**
