### PR TITLE
preseed: re-enable lazy_inode_init (for some reason disabled in focal)

### PR DESCRIPTION
**Pull request by CragW**

### CODE REVIEW

**Comment by CragW** [comment]
The primary preference is respect to [mke2fs ](https://github.com/tytso/e2fsprogs/blob/master/misc/mke2fs.c) which has `lazy_itable_init` enabled with modern kernel support, this PR intentionally specifying it in the answer file is an alternative consideration.  @fourdollars @alex-tu-cc

**Comment by fourdollars** [comment]
It will affect the power consumption so we disabled it.

**Comment by CragW** [comment]
Disabling `lazy_itable_init` is still required though `tlp` configuration already applied? Alternatively, can we exclude `nvme` device type?

**Comment by fourdollars** [comment]
Enabling lazy_itable_init will make the filesystem formating delayed even after the OOBE for the bigger storage no matter what kind of storage device.
The filesystem formating process will be slowly processing so we don't even know when it will finish from the UI unless we use some command to check it.
When ODM or some third party is doing the power consumption measuring while the formating process is still running, it will definitely increase the power consumption.
And it will also bring other bad side effects for the QA automation process so we decided to disable it.
It is better to disable it for all Ubuntu series.

**Pull request closed without merging**
