### PR TITLE
Nobulate after target_chroot.sh again to ensure the BootOrder is corr…

### PR DESCRIPTION
**Pull request by fourdollars**
…ect.

### CODE REVIEW

**Comment by CragW** [comment]
It looks like something potentially altering the grub entries during target_chroot.sh stage therefore re-ordering it again to assure PEBOOT on next?

**Comment by fourdollars** [comment]
Yes

**Comment by fourdollars** [comment]
@CragW Could you help to merge this pull reuqest into the master branch? The focal branch has merged it.

**Comment by CragW** [comment]
Travis ci blocking merge to main, am working on this.

**Pull request merged**
