### PR TITLE
It needs to use zstd -19 during image building.

### PR DESCRIPTION
**Pull request by fourdollars**
Check https://lists.ubuntu.com/archives/ubuntu-devel/2021-December/041726.html for details.

### CODE REVIEW

**Comment by CragW** [comment]
From the read of given link, using `-19` will take longer time and larger memory usage, isn't it?

**Comment by fourdollars** [comment]
Yes, but it will also generate the smallest initrd.

**Comment by CragW** [comment]
In general, `-1` has a compromise result among the test reports.
https://github.com/waveform80/compression/blob/master/analysis.ipynb

The default compression level for `jammy` has been changed to `-1` from `-19`, at the time updating the ramdisk the new algorithm will apply. Typically we can keep it `-1` for the factory and first couple times boot.

https://git.launchpad.net/ubuntu/+source/initramfs-tools/commit/?h=ubuntu/jammy&id=b26f0be88481273dd69189ea3d9494966ae9328d

**Comment by fourdollars** [comment]
The change is for dell-bto images building and the recovery media creating. 
It won't affect the end user daily usage.

**Comment by alex-tu-cc** [comment]
@CragW how do you think of @fourdollars 's latest comment? It sounds better to just follow the instruction used for stock Ubuntu to minimize the gap between OEM image and stock Ubuntu.

**Comment by fourdollars** [comment]
What I was trying to highlight is `- zstd -19 during image building` from https://lists.ubuntu.com/archives/ubuntu-devel/2021-December/041726.html.

**Comment by CragW** [comment]
According to the measurement, using `-19` for image building will increase boot time in the factory runs unitl the new `initramfs-tools` recreating the ramdisk. We can keep it in line with stock Ubuntu uses as is `-1` unless a strong need of minimized size of ramdisk.

**Comment by fourdollars** [comment]
OK. Let me revert it in Somerville PPA.

**Pull request closed without merging**
