### PR TITLE
Switch ESP from FAT16 to FAT32 and correct RP partition name to OS.

### PR DESCRIPTION
**Pull request by cyruslien**
The output of `parted -l`:

Number  Start   End     Size    File system  Name                  Flags
 1      24.6kB  270MB   270MB   fat32        EFI System Partition  boot, esp
 2      270MB   8462MB  8192MB  fat32        OS                    msftres
 3      8472MB  1999GB  1991GB  ext4

### CODE REVIEW

**Comment by cyruslien** [comment]
@CragW,
Please help to review it, thank you!

**Comment by CragW** [comment]
Would you like to send another commit to replace `mkfs.msdos` with `mkfs.vfat`?

**Comment by cyruslien** [comment]
> Would you like to send another commit to replace `mkfs.msdos` with `mkfs.vfat`?

@CragW, 
Hi, Switched to mkfs.vfat and explicitly specify FAT-SIZE to 32 when formatting the partition (otherwise, laptop SKUs still formatted as FAT16). Please help to review it, Thanks

**Review by CragW — APPROVED** [review]

**Comment by CragW** [comment]
> > Would you like to send another commit to replace `mkfs.msdos` with `mkfs.vfat`?
> 
> @CragW, Hi, Switched to mkfs.vfat and explicitly specify FAT-SIZE to 32 when formatting the partition (otherwise, laptop SKUs still formatted as FAT16). Please help to review it, Thanks

@cyruslien, thank you for the patch with fixes.

**Pull request merged**
